# Generated by Django 6.0.2 on 2026-05-18 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=50)),
                ('sample_indicator', models.IntegerField(default=0)),
                ('sample_date', models.DateTimeField(verbose_name='Sample Date')),
            ],
        ),
        migrations.CreateModel(
            name='SamplesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=50)),
                ('sample_result', models.BooleanField(default=True)),
                ('sample_date', models.DateTimeField(verbose_name='Sample Date')),
                ('samples', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samplesAnalyzer.samples')),
            ],
        ),
    ]
