# Generated by Django 6.0.2 on 2026-05-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesAnalyzer', '0004_alter_result_result_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samples',
            old_name='sample_indicator',
            new_name='sample_pacient_name',
        ),
    ]
