# Generated by Django 6.0.2 on 2026-05-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesAnalyzer', '0005_rename_sample_indicator_samples_sample_pacient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='sample_pacient_name',
            field=models.CharField(max_length=50),
        ),
    ]
