# Generated by Django 6.0.2 on 2026-05-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesAnalyzer', '0006_alter_samples_sample_pacient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='sample_image',
            field=models.ImageField(blank=True, null=True, upload_to='samples/'),
        ),
    ]
